### ISSUE TITLE
Chyba v metodě removeSubscriber()

### ISSUE THREAD

**Issue by kockodev** [Ecomailcz/ecomail-php#2]
Máte chybu v metodě "removeSubscriber", která nekoresponduje s dokumentací API. Metodě DELETE nelze předat žádný parametr, avšak pro odhlášení uživatele z listu je potřeba předat argument "email".

Pokud udělám opravu, bude schválen Pull-Request?

**Comment by matoni555** [comment]
+1

**Comment by kockodev** [comment]
ping @Tlapi

**Comment by Tlapi** [comment]
Tohle nám uniklo, omluva @rapemer 

Pull-request rádi schválíme, pokud máte ještě zájem. V opačném případě metodu upravíme sami co nejdříve.

**Comment by kockodev** [comment]
@Tlapi 
bohužel na to teď nebudu mít čas, reakce byla celkem dlouhá :-) pokud bych se k tomu dostal dříve než vy, tak dám informaci (ale během 3-4 týdnů se k tomu nedostanu...)

**Comment by lyk-antrop** [comment]
@Tlapi 
Taky jsem hitnul tenhle bug. Oprava ca 4 řádky, můžu buď pull request nebo poslat patch, pokud je ještě zájem.

**Comment by Tlapi** [comment]
@lyk-antrop Jasně, pošlete, rádi mergnem.

**Comment by kockodev** [comment]
@lyk-antrop, @Tlapi díky za opravu i merge .. tenhle issue se může zavřít :+1:
