### ISSUE TITLE
Requesty ve formátu JSON

### ISSUE THREAD

**Issue by bednee** [Ecomailcz/ecomail-php#21]
Toto je přímo z mailu, který jste mi poslali:

vidím, že k nám zasíláte kontakty v podobě x-www-form-urlencoded, jak je psáno v dokumentaci API, je potřeba requesty zasílat jako Content-Type:application/json.

Tato knihovna ale posílá x-www-form-urlencoded.

**Comment by jakubboucek** [comment]
Opraveno ve [verzi 1.2](https://github.com/Ecomailcz/ecomail-php/releases/tag/v1.2)

**Comment by bednee** [comment]
Nechtělo by ještě
`
if (is_array($data)) {
            curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));
        }
`
nahradit `json_encode`? Lokálně jsem to takto udělal a funguje to.
