### ISSUE TITLE
json_decode(): Depth must be greater than zero

### ISSUE THREAD

**Issue by MichalOdchazel** [Ecomailcz/ecomail-php#36]
Jsou dva problémy v knihovně:
```
Notice: Undefined variable: options in /var/www/html/vendor/ecomailcz/ecomail/src/Ecomail.php on line 491

Warning: json_decode(): Depth must be greater than zero in /var/www/html/vendor/ecomailcz/ecomail/src/Ecomail.php on line 491
```
Používáme PHP 7.4.*

**Comment by jakubboucek** [comment]
Ano, vím o tom, opravil jsem to v #33  a #34 a čekám na jejich merge.

Bohužel urguju Ecomail od května (4 měsíce), aby vydali nový release, ale dostal jsem odpověď, že jsou vytíženi. Do určité míry je to pochopitelné. Na moji další urgenci, že knihovna je nepoužitelná jsem dostal odpověď od podpory:

> Dle informací není knihovna v nepoužitelném stavu, jelikož jí používají ostatní klienti pro své integrace, pokud by v ní byly však takové překážky, doporučil bych napojení přímo přes api.

Prosím @MichalOdchazel, napište Ecomailu na support@ecomail.cz jaké potíže s knihovnou máte, snad Váš hlas pomůže vyjádřit závažnost chyby – vývojáři bohužel mají pocit, že problémy jsou kosmetické. My jsme zatím museli přejít na vlastní privátní fork knihovny, který jsme si opravili, Vám do té doby doporučím stejný postup. :-(

**Comment by jakubboucek** [comment]
Vyřešeno v rámci #33 a #34.
