### ISSUE TITLE
Bad condition on response format

### ISSUE THREAD

**Issue by Degee** [Ecomailcz/ecomail-php#7]
https://github.com/Ecomailcz/ecomail-php/blob/da03470bd773e15d78f6e3bf52fb6584ca1070f0/src/Ecomail.php#L445

There is a problem with this condition. When i use getListsCollection () method and i have more than one list defined, i got from json_decode () function 'array of stdClasses'.

@Tlapi, @filipsedivy you could at least make  **function send() protected**, i want to inherit it and build responseDataObject to unify return type of all methods.

Thanks

**Comment by jakubboucek** [comment]
Hi @Degee, I am NOT an author of package, but I tried to fix it for own company. 

Please check if changes in #18 helps you and send resume to #18 comments. Thanks.
